### ISSUE TITLE
Pass an object to directive handlers

### ISSUE THREAD

**Issue by ryangjchandler** [ryangjchandler/lowland#1]
Currently, you can accept 4 parameters to a directive's handler. This could get long and messy so I thought instead it would be nice to pass an object with some fixed names and allow the developer to destructure it and accept the ones they need.

Removes the need for any `_` parameter names.

**Comment by ryangjchandler** [comment]
@HugoDF could maybe do this as part of #3... I think it's a nicer pattern overall.

**Comment by HugoDF** [comment]
I'll have a look tomorrow 🙂

**Comment by ryangjchandler** [comment]
Yeah, I had an each/for implementation in an early commit but removed it, could just take that.

**Comment by HugoDF** [comment]
Similar APIs as Alpine, but delivered in a modular fashion 👍👍👍

Could have a `Lowland.use(plugin)` where plugin is a function that takes the Lowland instance. Since there's just 1 global Lowland instance that's probably not even necessary.

**Comment by ryangjchandler** [comment]
I figured something like `Lowland.use()` or `Lowland.extend()` would take an object, with perhaps a `directives` property which itself is an object of key/values for each directive and its handler.

Idk why, but the `.extend()` method is more appealing, never liked the `Vue.use()` name.

**Comment by ryangjchandler** [comment]
This is the commit where I removed the for implementation, just for reference. https://github.com/ryangjchandler/lowland/commit/49a27f7318b6f9e866471abfefa134a37924a81c

Was really naïve in that it didn't do any single root element checks or anything and also doesn't rely on `<template>`. 

The current renderer will check for a `__no_walk` property on the element and skip walking it too, as opposed to the previous `$child` check.
